version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - quizy-mongo:/data/db
    networks:
      - quizy-net

  keycloak:
    image: quay.io/keycloak/keycloak
    command: start-dev
    ports:
      - "8091:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123
    volumes:
      - keycloak-data:/opt/keycloak/data
    networks:
      - quizy-net

  auth-service:
    build: ./auth-service
    container_name: quizy-auth-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_DB_NAME=quizDB_auth
      - KEYCLOAK_BASE_URL=http://keycloak:8080
      - KEYCLOAK_ISSUER_URL=http://keycloak:8080
      - KEYCLOAK_REALM=QUIZY-PEAZY
      - KEYCLOAK_CLIENT_ID=quizy-peazy-client
      - KEYCLOAK_CLIENT_SECRET=TxolbRHSEUm7bKGoVgp62vL3QtCdu4dc
      - KEYCLOAK_ADMIN_USERNAME=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123
    depends_on:
      - mongo
      - keycloak
    networks:
      - quizy-net

  question-service:
    build: ./question-service
    container_name: quizy-question-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_DB_NAME=quizDB_questions
      - AUTH_SERVICE_URL=http://auth-service:3001
    depends_on:
      - mongo
      - auth-service
    networks:
      - quizy-net

  game-session-service:
    build: ./game-session-service
    container_name: quizy-game-session-service
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_DB_NAME=quizDB_game_sessions
      - AUTH_SERVICE_URL=http://auth-service:3001
      - QUESTION_SERVICE_URL=http://question-service:3002
    depends_on:
      - mongo
      - auth-service
      - question-service
    networks:
      - quizy-net

  realtime-service:
    build: ./realtime-service
    container_name: quizy-realtime-service
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
      - CORS_ORIGIN=http://localhost:3000
    networks:
      - quizy-net

volumes:
  quizy-mongo:
  keycloak-data:

networks:
  quizy-net:
    driver: bridge